// <auto-generated />
using System;
using Mashroo3i.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mashroo3i.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mashroo3i.Models.BusinessIdea", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessTypeReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("text");

                    b.Property<string>("Provinces")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("submitted");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Usp")
                        .HasColumnType("text");

                    b.HasKey("IdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("BusinessIdeas");
                });

            modelBuilder.Entity("Mashroo3i.Models.EvaluationScores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concerns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionScore")
                        .HasColumnType("integer");

                    b.Property<int>("FinancialScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<int>("InnovationScore")
                        .HasColumnType("integer");

                    b.Property<int>("MarketScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("EvaluationScores");
                });

            modelBuilder.Entity("Mashroo3i.Models.FinancialProjection", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ARR")
                        .HasColumnType("numeric");

                    b.Property<int>("BreakEvenMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("BreakEvenUnits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CAC")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustomersPerMonth")
                        .HasColumnType("numeric");

                    b.Property<string>("FinancialSummary")
                        .HasColumnType("text");

                    b.Property<decimal>("GrossMarginPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LTV")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LtvCacRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyGrowthRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoiPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TicketSize")
                        .HasColumnType("numeric");

                    b.HasKey("PlanId");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("FinancialPlans");
                });

            modelBuilder.Entity("Mashroo3i.Models.MarketAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitorAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompetitorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DifferentiationAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FatalFlaws")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LikelyFailureMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketOpportunitiesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketTrend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketTrendReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Saturation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("MarketAnalyses");
                });

            modelBuilder.Entity("Mashroo3i.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Mashroo3i.Models.SwotAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Opportunities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Threats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("SwotAnalyses");
                });

            modelBuilder.Entity("Mashroo3i.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("BusinessInterest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EvaluationCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Entrepreneur");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mashroo3i.Models.BusinessIdea", b =>
                {
                    b.HasOne("Mashroo3i.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mashroo3i.Models.EvaluationScores", b =>
                {
                    b.HasOne("Mashroo3i.Models.BusinessIdea", "BusinessIdea")
                        .WithOne("EvaluationScores")
                        .HasForeignKey("Mashroo3i.Models.EvaluationScores", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessIdea");
                });

            modelBuilder.Entity("Mashroo3i.Models.FinancialProjection", b =>
                {
                    b.HasOne("Mashroo3i.Models.BusinessIdea", "BusinessIdea")
                        .WithOne("FinancialPlan")
                        .HasForeignKey("Mashroo3i.Models.FinancialProjection", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessIdea");
                });

            modelBuilder.Entity("Mashroo3i.Models.MarketAnalysis", b =>
                {
                    b.HasOne("Mashroo3i.Models.BusinessIdea", "BusinessIdea")
                        .WithOne("MarketAnalysis")
                        .HasForeignKey("Mashroo3i.Models.MarketAnalysis", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessIdea");
                });

            modelBuilder.Entity("Mashroo3i.Models.Payment", b =>
                {
                    b.HasOne("Mashroo3i.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mashroo3i.Models.SwotAnalysis", b =>
                {
                    b.HasOne("Mashroo3i.Models.BusinessIdea", "BusinessIdea")
                        .WithOne("SwotAnalysis")
                        .HasForeignKey("Mashroo3i.Models.SwotAnalysis", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessIdea");
                });

            modelBuilder.Entity("Mashroo3i.Models.BusinessIdea", b =>
                {
                    b.Navigation("EvaluationScores");

                    b.Navigation("FinancialPlan");

                    b.Navigation("MarketAnalysis");

                    b.Navigation("SwotAnalysis");
                });
#pragma warning restore 612, 618
        }
    }
}
